{pkgs, ...}: {
  imports = [
    ./colorscheme.nix
    ./treesitter.nix
    ./telescope.nix
    ./lualine.nix
    ./bufferline.nix
    ./cmp.nix
    ./dressing.nix
    ./oil.nix
    ./oil-git.nix
    ./hop.nix
    ./quickfix.nix
    ./gh-qf.nix
    ./jj-qf.nix
    ./gitsigns.nix
    ./which-key.nix
    ./toggleterm.nix
    ./todo-comments.nix
    ./neogen.nix
    ./conform.nix
    ./multicursors.nix
    ./misc.nix
    ./exrc.nix
    ./extra-plugins.nix
    ./jj.nix
    ./99.nix
    ./sidekick.nix
    ./render-markdown.nix
    ./orgmode.nix
    ./image.nix
    ./reticle.nix
    ./bookmarks.nix
    ./haskell-tools.nix
    ./scripture.nix
    ./no-neck-pain.nix
    ./prompt-yank.nix
    ./better-escape.nix
  ];
}
